# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'run_desc.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow2(object):
    def setupUi2(self, MainWindow2):
        MainWindow2.setObjectName("MainWindow2")
        MainWindow2.resize(842, 661)
        MainWindow2.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow2)
        self.centralwidget.setObjectName("centralwidget")
        self.BeforeRunLabel = QtWidgets.QLabel(self.centralwidget)
        self.BeforeRunLabel.setGeometry(QtCore.QRect(80, 160, 81, 16))
        self.BeforeRunLabel.setObjectName("BeforeRunLabel")
        self.RunDescLabel = QtWidgets.QLabel(self.centralwidget)
        self.RunDescLabel.setGeometry(QtCore.QRect(150, 160, 441, 16))
        self.RunDescLabel.setText("")
        self.RunDescLabel.setObjectName("RunDescLabel")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(80, 80, 691, 30))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.NameTxtLabel = QtWidgets.QLabel(self.layoutWidget)
        self.NameTxtLabel.setObjectName("NameTxtLabel")
        self.horizontalLayout.addWidget(self.NameTxtLabel)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.horizontalLayout.addWidget(self.lineEdit_2)
        self.pushButton = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.layoutWidget1 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget1.setGeometry(QtCore.QRect(80, 210, 375, 30))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.TimeULabel = QtWidgets.QLabel(self.layoutWidget1)
        self.TimeULabel.setObjectName("TimeULabel")
        self.horizontalLayout_2.addWidget(self.TimeULabel)
        self.lineEdit = QtWidgets.QLineEdit(self.layoutWidget1)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_2.addWidget(self.lineEdit)
        self.pushButton_2 = QtWidgets.QPushButton(self.layoutWidget1)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_2.addWidget(self.pushButton_2)
        self.pushButton_10 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_10.setGeometry(QtCore.QRect(60, 520, 93, 28))
        self.pushButton_10.setObjectName("pushButton_10")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(630, 200, 73, 22))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(500, 520, 295, 30))
        self.widget.setObjectName("widget")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.pushButton_9 = QtWidgets.QPushButton(self.widget)
        self.pushButton_9.setObjectName("pushButton_9")
        self.horizontalLayout_6.addWidget(self.pushButton_9)
        self.pushButton_3 = QtWidgets.QPushButton(self.widget)
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_6.addWidget(self.pushButton_3)
        self.widget1 = QtWidgets.QWidget(self.centralwidget)
        self.widget1.setGeometry(QtCore.QRect(80, 370, 342, 30))
        self.widget1.setObjectName("widget1")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.widget1)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.pushButton_6 = QtWidgets.QPushButton(self.widget1)
        self.pushButton_6.setObjectName("pushButton_6")
        self.horizontalLayout_5.addWidget(self.pushButton_6)
        self.pushButton_7 = QtWidgets.QPushButton(self.widget1)
        self.pushButton_7.setObjectName("pushButton_7")
        self.horizontalLayout_5.addWidget(self.pushButton_7)
        self.widget2 = QtWidgets.QWidget(self.centralwidget)
        self.widget2.setGeometry(QtCore.QRect(80, 250, 272, 30))
        self.widget2.setObjectName("widget2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget2)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pushButton_8 = QtWidgets.QPushButton(self.widget2)
        self.pushButton_8.setObjectName("pushButton_8")
        self.horizontalLayout_3.addWidget(self.pushButton_8)
        self.pushButton_4 = QtWidgets.QPushButton(self.widget2)
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout_3.addWidget(self.pushButton_4)
        self.widget3 = QtWidgets.QWidget(self.centralwidget)
        self.widget3.setGeometry(QtCore.QRect(80, 310, 388, 30))
        self.widget3.setObjectName("widget3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widget3)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label = QtWidgets.QLabel(self.widget3)
        self.label.setObjectName("label")
        self.horizontalLayout_4.addWidget(self.label)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.widget3)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.horizontalLayout_4.addWidget(self.lineEdit_3)
        self.pushButton_5 = QtWidgets.QPushButton(self.widget3)
        self.pushButton_5.setObjectName("pushButton_5")
        self.horizontalLayout_4.addWidget(self.pushButton_5)
        MainWindow2.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow2)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 842, 26))
        self.menubar.setObjectName("menubar")
        MainWindow2.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow2)
        self.statusbar.setObjectName("statusbar")
        MainWindow2.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow2)

    def retranslateUi(self, MainWindow2):
        _translate = QtCore.QCoreApplication.translate
        MainWindow2.setWindowTitle(_translate("MainWindow2", "Run Description"))
        self.BeforeRunLabel.setText(_translate("MainWindow2", "Run Desc."))
        self.NameTxtLabel.setText(_translate("MainWindow2", "Path of .txt"))
        self.pushButton.setText(_translate("MainWindow2", "Browse"))
        self.TimeULabel.setText(_translate("MainWindow2", "Enter time underscore"))
        self.pushButton_2.setText(_translate("MainWindow2", "Calculate peaks before filter"))
        self.pushButton_10.setText(_translate("MainWindow2", "Quit"))
        self.comboBox.setCurrentText(_translate("MainWindow2", "Dyes"))
        self.comboBox.setItemText(0, _translate("MainWindow2", "Dyes"))
        self.comboBox.setItemText(1, _translate("MainWindow2", "R Int"))
        self.comboBox.setItemText(2, _translate("MainWindow2", "Y Int"))
        self.comboBox.setItemText(3, _translate("MainWindow2", "B Int"))
        self.comboBox.setItemText(4, _translate("MainWindow2", "G Int"))
        self.comboBox.setItemText(5, _translate("MainWindow2", "R"))
        self.comboBox.setItemText(6, _translate("MainWindow2", "Y"))
        self.comboBox.setItemText(7, _translate("MainWindow2", "B"))
        self.comboBox.setItemText(8, _translate("MainWindow2", "G"))
        self.pushButton_9.setText(_translate("MainWindow2", "Continue"))
        self.pushButton_3.setText(_translate("MainWindow2", "Back"))
        self.pushButton_6.setText(_translate("MainWindow2", "Show all filtered peaks"))
        self.pushButton_7.setText(_translate("MainWindow2", "Show filtered internal std. peaks"))
        self.pushButton_8.setText(_translate("MainWindow2", "Show All Peaks"))
        self.pushButton_4.setText(_translate("MainWindow2", "Show all internal std. peaks"))
        self.label.setText(_translate("MainWindow2", "Min. Height Filter"))
        self.pushButton_5.setText(_translate("MainWindow2", "Calculate peaks after filter"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow2 = QtWidgets.QMainWindow()
    ui = Ui_MainWindow2()
    ui.setupUi2(MainWindow2)
    MainWindow2.show()
    sys.exit(app.exec_())
